// src/app/react/react_app_component.tsx
import * as React from 'react'
import { DiamondsList } from '../shared/models/diamond.model'
import GridAllDiamondsCompnent from '../react/reactComponents/tsx/react_GridAllDiamondsCompnent'
import 'node_modules/bootstrap/dist/css/bootstrap.min.css';
import StatisticCompnent from './reactComponents/tsx/react_StatisticCompnent';
import HeaderCompnent from './reactComponents/tsx/react_HeaderCompnent';
import AddDiamondCompnent from './reactComponents/tsx/react_AddDiamondCompnent';
import toast, { Toaster } from 'react-hot-toast';
import { useState } from 'react';
import { Diamond } from 'angular-react/src/app/shared/models/diamond.model';
import ErrorPageCompnent from './reactComponents/tsx/react_errorPageCompnent';


const React_App_Component = () => {

    const [diamondsList, setTheArray] = useState<DiamondsList>([{} as Diamond]);
    const [pageStatus, setPageStatus] = useState<number>(1);
    
    React.useEffect(() => {
        var diamondsListFromFetch: DiamondsList=[];
        //get all data (the better way to that in big data is by paging)
        fetch('http://localhost:4200/GetAllDiamonds', {
            method: 'get',
            headers: {
              "Accept": "application/json",
              "Content-type": "application/json"
            },
          })
            .then(res => {
              if(res.ok)
              {
                return res.json();
              }
              console.log(`error when trying get data: api return error status: ${res.status}`);
              throw res.statusText;
            })
            .then(resp => {
              if(resp.errorCode=='500'){
                throw resp.errorDesc;
              }
              resp.forEach((element: Diamond) => {
                diamondsListFromFetch.push(element);
              });
              //(render again)
              setTheArray(diamondsListFromFetch);
              setPageStatus(1);
          }).catch(err =>
            {console.log(`error when trying get data: ${err}`);
            setPageStatus(2);});
      }, []);
    
    //i can send the 'setPageStatus' in props for more error handling (i was do that 'PageStatus' 2 it is 'loadingPage' but from now i choose to delete it)
    //i am considering another way to handle inside dives and not just global
    if(pageStatus==1)//sucsess
    {
        return (
        
            <div className="container-fluid h-100 d-flex flex-column justify-content-start">
                <HeaderCompnent />
                <StatisticCompnent diamondsList={diamondsList} />
                <GridAllDiamondsCompnent diamondsList={diamondsList} />
                <AddDiamondCompnent setTheArray={setTheArray} diamondsList={diamondsList} />
                <Toaster/>
            </div>
        )
    }
    else//error
    {
        return(
        <ErrorPageCompnent/>
        )
    }

}

export default React_App_Component;

// src/app/app.component.tsx
import { AfterViewInit, Component, OnChanges, OnDestroy, OnInit, SimpleChanges } from '@angular/core';
import * as React from 'react';

import * as ReactDOM from 'react-dom';
import ErrorPageCompnent from './react/reactComponents/tsx/react_errorPageCompnent';

import React_App_Component from './react/react_app_component';
import { Diamond, DiamondsList } from './shared/models/diamond.model';


@Component({
  selector: 'app-root',
  template: '<div [id]="rootId"></div>',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnChanges, AfterViewInit, OnDestroy  {
  title = 'angularreactapp';
  public rootId = 'root';
  
  constructor( ) {}


  ngOnChanges(changes: SimpleChanges) {
    debugger;
    this.render();

  }

   async ngAfterViewInit() {
    this.render();
  }

  ngOnDestroy() {

  }

  private async render() {
    var diamondsList: DiamondsList= await this.GetAllDiamonds();
    if(diamondsList.length>0)
    {
      ReactDOM.render(React.createElement(React_App_Component,diamondsList), document.getElementById(this.rootId));
    }
    else
    {
      ReactDOM.render(React.createElement(ErrorPageCompnent), document.getElementById(this.rootId));
    }
  }

  async GetAllDiamonds() {
    var diamondsList1: DiamondsList=[]
   await fetch('http://localhost:4200/GetAllDiamonds', {
    method: 'get',
    headers: {
      "Accept": "application/json",
      "Content-type": "application/json"
    },
    // (var) payload looks like this {Header: "Sending", . . .} 
  })
    .then(res => {
      if(res.ok)
      {
        return res.json();
      }
      alert(`error when trying get data: api return error status: ${res.status}`);
      throw res.statusText;
    })
    .then(resp => {
      if(resp.errorCode=='500'){
        throw resp.errorDesc;
      }
      resp.forEach((element: Diamond) => {
        diamondsList1.push(element);
      });
      //return diamondsList1;
  }).catch(err =>alert(`error when trying get data: ${err}`));
  
    return diamondsList1;
}

}
